<?php $this->widget('zii.widgets.CDetailView', array(
	'data'=>$model,
	'formatter'=>new Formatter,
	'attributes'=>array(
		'name',
		'street',
		'land_registry_number',
		'house_number',
		'postal_code',
		'city',
		array(
			'name'=>'region',
			'value'=>DropDownItem::item('Organisation.region', $model->region),
			'type'=>'raw',
		),
		'company_id_number',
		'vat_id_number',
		'representative',
		'email:email',
		'telephone',
		'fax',
		'www:url',
		'bank_account_number',
		'revenue_authority',
		'worker_name',
		'worker_telephone',
		'worker_fax',
		'worker_email:email',
	),
)); ?>
